trigger: none

schedules:
- cron: '30 6 * * MON-FRI'
  displayName: Daily Morning run
  branches:
    include:
    - main
  always: true

pool:
  vmImage: ubuntu-24.04

steps:

- bash: python --version
  displayName: 'Python version'

- bash: pip install -r reqs.txt
  displayName: 'Install python libs'

- bash: pip freeze
  displayName: 'Display installed python libs'

- bash: pip install snowflake-cli==3.7.2 && snow --version
  displayName: 'Install snowpark'

- bash: python az_blob_move.py new processing
  displayName: 'Move new files to work dir'
  env:
     AZURE_CLIENT_ID: $(azure.client.id)
     AZURE_CLIENT_SECRET: $(azure.client.secret)
     AZURE_TENANT_ID: $(azure.tenant.id)

- bash: snow snowpark execute procedure "unpack_xmls()" -x
  displayName: 'Execute in Snowflake'
  env:
    SNOWFLAKE_ACCOUNT: $(snowflake.account)
    SNOWFLAKE_USER: $(snowflake.user)
    SNOWFLAKE_PASSWORD: $(snowflake.password)
    SNOWFLAKE_ROLE: $(snowflake.role)

- bash: python az_blob_move.py processing ingested
  displayName: 'Move ingested files out of work dir'
  env:
     AZURE_CLIENT_ID: $(azure.client.id)
     AZURE_CLIENT_SECRET: $(azure.client.secret)
     AZURE_TENANT_ID: $(azure.tenant.id)
